name: scot_api
description: A simple client to connect to the Scotbot interface of Hive tribes.
version: 0.4.3
repository: https://github.com/LeoFinance/scot-api

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  pool: ^1.5.1

dev_dependencies:
  build_runner: ^2.1.2
  faker: ^2.0.0
  json_serializable: ^6.2.0
  mockito: ^5.1.0
  test: ^1.21.0
  very_good_analysis: ^2.4.0
