name: scot_api
description: A simple client to connect to the Scotbot interface of Hive tribes.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.3
  json_annotation: ^4.1.0
  intl: ^0.17.0

dev_dependencies:
  test: ^1.17.12
  build_runner: ^2.1.2
  json_serializable: ^5.0.1
  faker: ^2.0.0
  mockito: ^5.0.16
